### ISSUE TITLE
Suggested Additions to the Awesome Audio List !

### ISSUE THREAD

**Issue by bennett-e** [DolbyIO/awesome-audio#11]
Code : How-To Edit Audio : Apps
- [Nuendo](https://www.steinberg.net/nuendo/) - DAW for MacOS and Windows that has support for Dolby Atmos and other forms of spatial audio.

Community : Podcasts
- [Dissect](https://dissectpodcast.com/) - Long form music analysis of albums that goes track by track discussing music theory and artist intention.

Industry : Standards
- [ITU-R BS.2159-7 ](https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-BS.2159-7-2015-PDF-E.pdf)- International Telecommunications Union (ITU) multi-channel speaker configurations for home and broadcast applications

**Comment by j12y** [comment]
Good suggestionos, go ahead and submit a PR and we can merge these in.
